# Generated by Django 2.0.9 on 2018-11-06 07:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_Name',
            new_name='Names',
        ),
        migrations.RemoveField(
            model_name='name',
            name='question',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
