# Generated by Django 2.0.9 on 2018-11-06 07:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('hello', '0002_auto_20181106_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='names',
            old_name='question_text',
            new_name='name_text',
        ),
    ]
